### ISSUE TITLE
Bug in nginx run task

### ISSUE THREAD

**Issue by Emerosn** [openwisp/ansible-openwisp-wifi-login-pages#33]
Hello!

TASK [openwisp.wifi_login_pages : enable nginx site] ********************************************************************************************************************
fatal: [wifi.ntonline.com.br]: FAILED! => {"changed": false, "gid": 0, "group": "root", "mode": "0644", "msg": "refusing to convert from file to symlink for /etc/nginx/sites-enabled/wifi_login_pages", "owner": "root", "path": "/etc/nginx/sites-enabled/wifi_login_pages", "size": 1881, "state": "file", "uid": 0}

PLAY RECAP **************************************************************************************************************************************************************
wifi.ntonline.com.br       : ok=26   changed=3    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

I tried to deploy today and discovered this error. When I checked the file /etc/nginx/sites-available/wifi_login_pages, I noticed that the value of server_name was incorrect:
server_name w i f i . n t o n l i n e . c o m . b r;
Throughout the deployment process, the domain keeps reverting to be incorrect again.

**Comment by nemesisdesign** [comment]
@Emerosn please share your playbook, it looks like a misconfiguration.

**Comment by Emerosn** [comment]
the playbook in userd is : ansible-galaxy install openwisp.wifi_login_pages

**Comment by nemesisdesign** [comment]
> the playbook in userd is : ansible-galaxy install openwisp.wifi_login_pages

The contents of the YAML playbook I meant.

**Comment by Emerosn** [comment]
this yml content for builder is here:

- hosts: openwisp-wifi-login-pages
  become: "{{ become | default('yes') }}"
  roles:
    - openwisp.wifi_login_pages
  vars:
    wifi_login_pages_domains: ["wifi.openwisp.org"]

**Comment by nemesifier** [comment]
Honestly I have no idea why this happens to you and I do not know how to help.

**Comment by nemesifier** [comment]
If you still have this issue, try with the latest master. If the issue persist, please provide a list of steps to replicate and we'll look into it. Thanks :pray:.
